### ISSUE TITLE
Remove the fu540 dt modification

### ISSUE THREAD

**Issue by atishp04** [riscv-software-src/opensbi#142]
Currently, we modify fu540 DT for following purpose.

1. Modify M mode IRQ context to 0xFFFFFFF so kernel won't try to parse them.
fixed in kernel now
https://patchwork.kernel.org/project/linux-riscv/list/?series=193125

2. Change hart0 status to disabled
Latest DT in Linux kernel already have it disabled.

3. Add chosen node for U-Boot serial console
It is now added to DT as well.
https://patchwork.kernel.org/patch/11182027/

We should remove the DT modifications but it can't be done now to avoid compatibility breakage. 
It should be done some time in the future. The issue is created to serve as a reminder.

**Comment by lbmeng** [comment]
I don't think we should do 2 and 3.

The fu540 is now used in QEMU 'sifive_u' machine, so DT fixup is needed because U-Boot/Linux will boot directly with QEMU's built-in DT.
