### ISSUE TITLE
Literature for OpenSBI

### ISSUE THREAD

**Issue by Laxitamali** [riscv-software-src/opensbi#198]
I am fairly new to RISCV. Can anyone give me good reference to understand/read OpenSBI?

**Comment by atishp04** [comment]
OpenSBI is fairly well documented. You can take a look at the docs section or the generated pdf in the released tar ball.
Here is an excellent deep dive talk by Anup.

https://www.youtube.com/watch?v=jstwB-o9ll0&ab_channel=RISC-VInternational

**Comment by axel-h** [comment]
Aside from this, there is https://github.com/riscv/riscv-sbi-doc with the general SBI background.
