### ISSUE TITLE
[help] how to build test payload for non-qemu target

### ISSUE THREAD

**Issue by yf13** [riscv-software-src/opensbi#340]
Hi,

I downloaded v1.3.1 release and can build and run the test payload with qemu-system-riscv64, this is great.

I have a T-Head c908 based device and I am wondering where I can find docs / guides to quickly build the test payload for trying?

I tried to use `FW_TEXT_START=0x8000000` on make command line but the generated `fw_payload.elf` still uses start address `0x80000000`  as per the `objdump` tool. 

Regards,
yf13

**Comment by SiFiveHolland** [comment]
There is no Makefile dependency to cause the firmware to be rebuilt when changing `FW_TEXT_START`. You could `touch firmware/fw_base.ldS` or delete the build directory to force a rebuild.

**Comment by yf13** [comment]
@SiFiveHolland thanks a lot. I got correct FW_TEXT_START with clean build now.
